name: rewrites
description: Helps pub serve to support apps using HTML5 pushState for navigation during development.
version: 0.1.0
author: Adao Junior <itsjunnior@gmail.com>
homepage: https://github.com/adaojunior/pub_serve_rewrites
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  shelf_proxy: "^0.1.0+2"
  args: "^0.13.2"
  yaml: "^2.1.7"
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
executables:
  rewrites: null
